//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro_Servicio
    {
        public int ServicioID { get; set; }
        public Nullable<int> CarroId { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<System.DateTime> FechaHoraIngreso { get; set; }
        public string ObservacionesEstado1 { get; set; }
        public string ObservacionesEstado2 { get; set; }
        public string ObservacionesEstado3 { get; set; }
        public string ObservacionesEstado4 { get; set; }
    
        public virtual Carro Carro { get; set; }
    }
}
