//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro_CarWash
    {
        public int CarWashId { get; set; }
        public Nullable<int> CarroId { get; set; }
        public Nullable<decimal> precio { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual Carro Carro { get; set; }
    }
}
