//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaJr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carro()
        {
            this.Carro_CarWash = new HashSet<Carro_CarWash>();
            this.Carro_Servicio = new HashSet<Carro_Servicio>();
        }
    
        public int CarroId { get; set; }
        public string Placa { get; set; }
        public Nullable<int> Modelo { get; set; }
        public Nullable<int> MarcaId { get; set; }
        public Nullable<int> ClienteId { get; set; }
        public Nullable<int> Activo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carro_CarWash> Carro_CarWash { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Marca Marca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carro_Servicio> Carro_Servicio { get; set; }
    }
}
